# Generated by Django 2.1.9 on 2019-06-22 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='商品名')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='値段')),
            ],
            options={
                'db_table': 'good',
            },
        ),
    ]
